<?php

// This file generated by Propel convert-props target on Fri Apr 10 20:08:30 2009
// from XML runtime conf file /home/lancewf/databaseCreator/persistence/runtime-conf.xml
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'animalkingdom' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'animalkingdom',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'tokyodisneyland' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'tokyodisneyland',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'buschgardenstampa' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'buschgardenstampa',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'disneyland' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'disneyland',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'parcdisneyland' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'parcdisneyland',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'epcot' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'epcot',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'hollywoodstudios' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'hollywoodstudios',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'islandsOfAdventure' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'islandsofadventure',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'knottsberryfarm' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'knottsberryfarm',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'legolandcalifornia' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'legolandcalifornia',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'magicmountain' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'magicmountain',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'overtexas' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'overtexas',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'seaworldorlando' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'seaworldorlando',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'tokyodisneysea' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'tokyodisneysea',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'universalStudiosFlorida' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'universalstudiosflorida',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'universalStudiosHollywood' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'universalstudioshollywood',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'waltdisneystudiospark' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'waltdisneystudiospark',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	
       'magickingdom' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'magickingdom',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	  
       'californiaadventure' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'californiaadventure',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'greatadventure' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'greatadventure',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	
       'greatamerica' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'greatamerica',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'overgeorgia' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'overgeorgia',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	 
       'discoverykingdom' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'discoverykingdom',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	
       'seaworldsanantonio' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'seaworldsanantonio',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	 
       'kentuckykingdom' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'kentuckykingdom',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'sixflagsamerica' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'sixflagsamerica',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	
       'canadaswonderland' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'canadaswonderland',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	
       'cedarpoint' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'cedarpoint',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	 
       'hersheypark' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'hersheypark',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
       'newengland' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'newengland',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),  
       'thorpepark' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'thorpepark',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),   
       'stlouis' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'stlouis',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),	      	      		      	     	      	
      'park' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'park',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
      'park2' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'park2',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
      'persistence' => 
	      	array 
	      	(
	        	'adapter' => 'mysql',
	        	'connection' => 
	        	array 
	        	(
	          		'phptype' => 'mysql',
	          		'database' => 'park',
	          		'hostspec' => 'coasterqcom.ipagemysql.com',
	          		'username' => 'phpuser',
	          		'password' => 'uJvQadbYwcBc3W3J',
	        	),
	      	),
	      	
      'default' => 'park',
    ),
  ),
);
