<?php

  // include base peer class
  require_once 'persistence/om/BaseLandPeer.php';

  // include object class
  include_once 'persistence/Land.php';


/**
 * Skeleton subclass for performing query and update operations on the 'land' table.
 *
 * a land in the park
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class LandPeer extends BaseLandPeer {

} // LandPeer
