<?php

require_once 'persistence/om/BaseRide.php';


/**
 * Skeleton subclass for representing a row from the 'ride' table.
 *
 * a ride in the park
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class Ride extends BaseRide {


    public function toJson()
    {
        $array_store = array ();
    
        $array_store["location"] = $this->getLand()->getName();
        $array_store["id"] = $this->getId();
        $array_store["name"] = $this->getName();
        $array_store["current"] = $this->getCurrentwaittime();
        $array_store["height"] = $this->getHeight();
        $array_store["fastpass"] = $this->getFastpass();
    
        return json_encode($array_store);
    }

} // Ride
