<?php

require_once 'persistence/om/BaseItineraryRide.php';


/**
 * Skeleton subclass for representing a row from the 'itinerary_ride' table.
 *
 * A ride on a itinerary
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class ItineraryRide extends BaseItineraryRide {

    public function toJson()
    {
        $array_store = array ();
    
        $array_store["priority"] = $this->getPriority();
        $array_store["rideId"] = $this->getRideId();
    
        return json_encode($array_store);
    }
	
} // ItineraryRide
