<?php

  // include base peer class
  require_once 'persistence/om/BaseItineraryRidePeer.php';

  // include object class
  include_once 'persistence/ItineraryRide.php';


/**
 * Skeleton subclass for performing query and update operations on the 'itinerary_ride' table.
 *
 * A ride on a itinerary
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class ItineraryRidePeer extends BaseItineraryRidePeer {

} // ItineraryRidePeer
