<?php

require_once 'persistence/om/BaseParkDay.php';


/**
 * Skeleton subclass for representing a row from the 'park_day' table.
 *
 * Information about one day in the park
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class ParkDay extends BaseParkDay {

} // ParkDay
