<?php

require_once 'persistence/om/BaseUser.php';


/**
 * Skeleton subclass for representing a row from the 'user' table.
 *
 * a user to the system
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:50 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class User extends BaseUser {

} // User
