<?php

require_once 'propel/om/BaseObject.php';

require_once 'propel/om/Persistent.php';


include_once 'propel/util/Criteria.php';

include_once 'persistence/ParkDayPeer.php';

/**
 * Base class that represents a row from the 'park_day' table.
 *
 * Information about one day in the park
 *
 * This class was autogenerated by Propel on:
 *
 * Wed Apr 14 18:59:08 2010
 *
 * @package    persistence.om
 */
abstract class BaseParkDay extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ParkDayPeer
	 */
	protected static $peer;


	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;


	/**
	 * The value for the date field.
	 * @var        int
	 */
	protected $date;


	/**
	 * The value for the open_hour field.
	 * @var        int
	 */
	protected $open_hour;


	/**
	 * The value for the open_min field.
	 * @var        int
	 */
	protected $open_min;


	/**
	 * The value for the close_hour field.
	 * @var        int
	 */
	protected $close_hour;


	/**
	 * The value for the close_min field.
	 * @var        int
	 */
	protected $close_min;


	/**
	 * The value for the is_closed field.
	 * @var        boolean
	 */
	protected $is_closed;


	/**
	 * The value for the crowd_level field.
	 * @var        int
	 */
	protected $crowd_level;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * Park Day Id
	 * @return     int
	 */
	public function getId()
	{

		return $this->id;
	}

	/**
	 * Get the [optionally formatted] [date] column value.
	 * date time of the park day information is for
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the integer unix timestamp will be returned.
	 * @return     mixed Formatted date/time value as string or integer unix timestamp (if format is NULL).
	 * @throws     PropelException - if unable to convert the date/time to timestamp.
	 */
	public function getDate($format = 'Y-m-d H:i:s')
	{

		if ($this->date === null || $this->date === '') {
			return null;
		} elseif (!is_int($this->date)) {
			// a non-timestamp value was set externally, so we convert it
			$ts = strtotime($this->date);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse value of [date] as date/time value: " . var_export($this->date, true));
			}
		} else {
			$ts = $this->date;
		}
		if ($format === null) {
			return $ts;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $ts);
		} else {
			return date($format, $ts);
		}
	}

	/**
	 * Get the [open_hour] column value.
	 * The hour that the park opens
	 * @return     int
	 */
	public function getOpenHour()
	{

		return $this->open_hour;
	}

	/**
	 * Get the [open_min] column value.
	 * The mins that the park opens
	 * @return     int
	 */
	public function getOpenMin()
	{

		return $this->open_min;
	}

	/**
	 * Get the [close_hour] column value.
	 * The hour that the park closes
	 * @return     int
	 */
	public function getCloseHour()
	{

		return $this->close_hour;
	}

	/**
	 * Get the [close_min] column value.
	 * The min that the park closes
	 * @return     int
	 */
	public function getCloseMin()
	{

		return $this->close_min;
	}

	/**
	 * Get the [is_closed] column value.
	 * is the park closed
	 * @return     boolean
	 */
	public function getIsClosed()
	{

		return $this->is_closed;
	}

	/**
	 * Get the [crowd_level] column value.
	 * The crowd level of the park
	 * @return     int
	 */
	public function getCrowdLevel()
	{

		return $this->crowd_level;
	}

	/**
	 * Set the value of [id] column.
	 * Park Day Id
	 * @param      int $v new value
	 * @return     void
	 */
	public function setId($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ParkDayPeer::ID;
		}

	} // setId()

	/**
	 * Set the value of [date] column.
	 * date time of the park day information is for
	 * @param      int $v new value
	 * @return     void
	 */
	public function setDate($v)
	{

		if ($v !== null && !is_int($v)) {
			$ts = strtotime($v);
			if ($ts === -1 || $ts === false) { // in PHP 5.1 return value changes to FALSE
				throw new PropelException("Unable to parse date/time value for [date] from input: " . var_export($v, true));
			}
		} else {
			$ts = $v;
		}
		if ($this->date !== $ts) {
			$this->date = $ts;
			$this->modifiedColumns[] = ParkDayPeer::DATE;
		}

	} // setDate()

	/**
	 * Set the value of [open_hour] column.
	 * The hour that the park opens
	 * @param      int $v new value
	 * @return     void
	 */
	public function setOpenHour($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->open_hour !== $v) {
			$this->open_hour = $v;
			$this->modifiedColumns[] = ParkDayPeer::OPEN_HOUR;
		}

	} // setOpenHour()

	/**
	 * Set the value of [open_min] column.
	 * The mins that the park opens
	 * @param      int $v new value
	 * @return     void
	 */
	public function setOpenMin($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->open_min !== $v) {
			$this->open_min = $v;
			$this->modifiedColumns[] = ParkDayPeer::OPEN_MIN;
		}

	} // setOpenMin()

	/**
	 * Set the value of [close_hour] column.
	 * The hour that the park closes
	 * @param      int $v new value
	 * @return     void
	 */
	public function setCloseHour($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->close_hour !== $v) {
			$this->close_hour = $v;
			$this->modifiedColumns[] = ParkDayPeer::CLOSE_HOUR;
		}

	} // setCloseHour()

	/**
	 * Set the value of [close_min] column.
	 * The min that the park closes
	 * @param      int $v new value
	 * @return     void
	 */
	public function setCloseMin($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->close_min !== $v) {
			$this->close_min = $v;
			$this->modifiedColumns[] = ParkDayPeer::CLOSE_MIN;
		}

	} // setCloseMin()

	/**
	 * Set the value of [is_closed] column.
	 * is the park closed
	 * @param      boolean $v new value
	 * @return     void
	 */
	public function setIsClosed($v)
	{

		if ($this->is_closed !== $v) {
			$this->is_closed = $v;
			$this->modifiedColumns[] = ParkDayPeer::IS_CLOSED;
		}

	} // setIsClosed()

	/**
	 * Set the value of [crowd_level] column.
	 * The crowd level of the park
	 * @param      int $v new value
	 * @return     void
	 */
	public function setCrowdLevel($v)
	{

		// Since the native PHP type for this column is integer,
		// we will cast the input value to an int (if it is not).
		if ($v !== null && !is_int($v) && is_numeric($v)) {
			$v = (int) $v;
		}

		if ($this->crowd_level !== $v) {
			$this->crowd_level = $v;
			$this->modifiedColumns[] = ParkDayPeer::CROWD_LEVEL;
		}

	} // setCrowdLevel()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (1-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      ResultSet $rs The ResultSet class with cursor advanced to desired record pos.
	 * @param      int $startcol 1-based offset column which indicates which restultset column to start with.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate(ResultSet $rs, $startcol = 1)
	{
		try {

			$this->id = $rs->getInt($startcol + 0);

			$this->date = $rs->getTimestamp($startcol + 1, null);

			$this->open_hour = $rs->getInt($startcol + 2);

			$this->open_min = $rs->getInt($startcol + 3);

			$this->close_hour = $rs->getInt($startcol + 4);

			$this->close_min = $rs->getInt($startcol + 5);

			$this->is_closed = $rs->getBoolean($startcol + 6);

			$this->crowd_level = $rs->getInt($startcol + 7);

			$this->resetModified();

			$this->setNew(false);

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = ParkDayPeer::NUM_COLUMNS - ParkDayPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating ParkDay object", $e);
		}
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      Connection $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ParkDayPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			ParkDayPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.  If the object is new,
	 * it inserts it; otherwise an update is performed.  This method
	 * wraps the doSave() worker method in a transaction.
	 *
	 * @param      Connection $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save($con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ParkDayPeer::DATABASE_NAME);
		}

		try {
			$con->begin();
			$affectedRows = $this->doSave($con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollback();
			throw $e;
		}
	}

	/**
	 * Stores the object in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      Connection $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave($con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ParkDayPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ParkDayPeer::doUpdate($this, $con);
				}
				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;
		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = ParkDayPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ParkDayPeer::DATABASE_NAME);

		if ($this->isColumnModified(ParkDayPeer::ID)) $criteria->add(ParkDayPeer::ID, $this->id);
		if ($this->isColumnModified(ParkDayPeer::DATE)) $criteria->add(ParkDayPeer::DATE, $this->date);
		if ($this->isColumnModified(ParkDayPeer::OPEN_HOUR)) $criteria->add(ParkDayPeer::OPEN_HOUR, $this->open_hour);
		if ($this->isColumnModified(ParkDayPeer::OPEN_MIN)) $criteria->add(ParkDayPeer::OPEN_MIN, $this->open_min);
		if ($this->isColumnModified(ParkDayPeer::CLOSE_HOUR)) $criteria->add(ParkDayPeer::CLOSE_HOUR, $this->close_hour);
		if ($this->isColumnModified(ParkDayPeer::CLOSE_MIN)) $criteria->add(ParkDayPeer::CLOSE_MIN, $this->close_min);
		if ($this->isColumnModified(ParkDayPeer::IS_CLOSED)) $criteria->add(ParkDayPeer::IS_CLOSED, $this->is_closed);
		if ($this->isColumnModified(ParkDayPeer::CROWD_LEVEL)) $criteria->add(ParkDayPeer::CROWD_LEVEL, $this->crowd_level);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ParkDayPeer::DATABASE_NAME);

		$criteria->add(ParkDayPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of ParkDay (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDate($this->date);

		$copyObj->setOpenHour($this->open_hour);

		$copyObj->setOpenMin($this->open_min);

		$copyObj->setCloseHour($this->close_hour);

		$copyObj->setCloseMin($this->close_min);

		$copyObj->setIsClosed($this->is_closed);

		$copyObj->setCrowdLevel($this->crowd_level);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a pkey column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     ParkDay Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ParkDayPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ParkDayPeer();
		}
		return self::$peer;
	}

} // BaseParkDay
