<?php

  // include base peer class
  require_once 'persistence/om/BasePropertyPeer.php';

  // include object class
  include_once 'persistence/Property.php';


/**
 * Skeleton subclass for performing query and update operations on the 'property' table.
 *
 * a property with a value
 *
 * This class was autogenerated by Propel on:
 *
 * Wed May 20 18:37:51 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class PropertyPeer extends BasePropertyPeer {

} // PropertyPeer
